#each new term in the fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,... By considering the terms in the fibonacci sequence whose value do not exceed four million, find the sum of the even-valued terms.

a = 1
e = 1
fibo = 0
sum_even_fibo = 0
while True:
    fibo = a+e
    a = e
    e = fibo
    if fibo % 2 == 0:
        sum_even_fibo += fibo

    # print(fibo)
    if sum_even_fibo > 4000000:
        break
print(sum_even_fibo)
